### ISSUE TITLE
Newby question: Opening files not working

### ISSUE THREAD

**Issue by GrigorijSchleifer** [holzschu/ios_system#137]
Holle community, first of all thank you holzschu for making such a powerful app. Really great work. 

I am new to programming and when attempting  to open a simple `*.txt` file to loop over it for a book exercise I get a `FileNotFoundError`. I am sure I am missing something trivial.

```console
[~/Documents/testdir]$ python open_file.py 
Traceback (most recent call last):
  File "/private/var/mobile/Containers/Data/Application/B7C98837-9423-45A4-A7E8-E17E40DF01AB/Documents/test
dir/open_file.py", line 1, in <module>
    with open("~/Documents/testdir/test_text.txt") as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '~/Documents/testdir/test_text.txt'
```
When I type `pwd` I get:

```console
[~/Documents/testdir]$ pwd
~/Documents/testdir
```

And listing the contents of the directory shows the files I am working on:

```console
[~/Documents/testdir]$ ls
open_file.py    test_text.txt
```

My python code in open_file.py is:

```python
with open("~/Documents/testdir/test_text.txt") as f:
    f = f.readlines()
    for ln in f:
        print(ln)
```

Where is the recommendet path to store all my files? And again, thank you for your hard work. 

Greetings from Bonn

Grigorij

**Comment by holzschu** [comment]
Python sends the argument of "open" directly to the "open()" function, without any pre-treatment. "open()" is a low level function, it does not check anything in the file name. So the function tries to open a file named, litterally, "~/Documents/testdir/test_text.txt" and finds that it doesn't exist. You need to first expand the "~" to its full value, using `os.path.expanduser("~/Documents/testdir/test_text.txt")`. 

Alternatively, you can replace "~"  with `os.environ["HOME"]`, as in: `open(os.environ["HOME"] + "/Documents/testdir/test_text.txt")`.

You could also use a local file path, rather than an absolute file path: `open("test_text.txt")`.

**Comment by GrigorijSchleifer** [comment]
Dear holzshu thank you very much. It dead work.

**Comment by GrigorijSchleifer** [comment]
Thank you
