### ISSUE TITLE
Is sshd available?

### ISSUE THREAD

**Issue by hugo-tubi** [holzschu/ios_system#154]
I see there are `sshd.c` in ssh_agent package. But `sshd` seems not available in system. It would be great to have it, so that can config things for a-shell via ssh from a full-keyboard computer.

**Comment by hugo-tubi** [comment]
closing. There is an sshd issue under https://github.com/holzschu/a-shell

**Comment by holzschu** [comment]
Hi, thanks for asking (and for cleaning up the issue afterwards).
I’ve tried adding `sshd` recently, but I ran into a lot of issues that I on’t know how to solve yet.
The problem is not `sshd` itself, but the configuration files and especially the host key. An iPhone or iPad is likely to change IP address regularly, and `ssh` does not like when the IP address changes and the host key doesn’t.
Nothing impossible to surmount, but still something I need to think about before release.
