### ISSUE TITLE
'libssh2.h' file not found

### ISSUE THREAD

**Issue by lyuwen** [holzschu/ios_system#65]
I check out the most recent release and try to build the curl_ios_static. But it failed on this. Any ideas why?
I did the `get_source.sh` and `get_frameworks.sh`.
Thank you.

**Comment by lyuwen** [comment]
I guess it just needs to be
```
#include <libssh2/libssh2.h>
```
. There are other issues with `curl_ios_static`, the head files for blink related stuff BK*.h are not properly linked and XCode cannot find then either. There can be simple workaround though.
Are this repository actively developed now?

**Comment by holzschu** [comment]
The repository is actively developed, yes. 
I should point out that curl_ios_static is only designed to work within blink (it is static in order to have access to blink key management system). For all other uses, I recommend the dynamic framework (curl.framework).

For curl_ios_static, you need to clone blink, then download ios_system frameworks using blink associated scripts.

**Comment by holzschu** [comment]
I'm trying to reproduce the issue. 

I'm thinking we may have missed the obvious answer here: you don't need to build curl_ios_static. The command is integrated into the Blink target. That is: if you simply build "Blink", the main target, you should have a working application, with the curl command integrated (try "curl parrot.live" to check).

**Comment by holzschu** [comment]
Is this issue still active?
