### ISSUE TITLE
Logic of waitpid seems incorrect

### ISSUE THREAD

**Issue by terrychou** [holzschu/ios_system#89]
https://github.com/holzschu/ios_system/blob/88fb6f9bd1e22e3861b238a999f557454ffbfdb1/libc_replacement.c#L219-L228

As shown above, it is possible that the related thread had already been done when `waitpid` is called, which will make the code jump to `line 224`. But in this case, `waitpid` should return the `pid`, rather than `-1` as in `line 227`.

**Comment by holzschu** [comment]
There were some changes to `iOS_system` that had not been committed yet. I've just pushed them. They deal mostly with the case of `waitpid` being called before the thread is actually started (it happens, too).

I had trouble with the `waitpid` man page. I read it again, and I think you are right: line 227 should return `pid`.

**Comment by terrychou** [comment]
Just pulled the latest project and built, it works correctly now. Thanks for the update.

I found this problem because it would make my calling code wait forever for the "child" thread, and never see the hope. :)

By the way, there is a warning showing `Failed to increased file descriptor limit to = 1024` every time. What would be the cause?

**Comment by holzschu** [comment]
That is odd.
I keep track of the number of active file descriptors (lines 1744 - 1750) and make sure there are at least 128 file descriptors available (line 1755) before I start a command, otherwise I increase the number of active file descriptors (line 1757) with setrlimit. This line should not fail, but when it does, it prints this warning. These lines are here because some commands (jupyter notebook) open a large number of sockets (more than 60) for internal communication. It is not vital for normal commands.

The problem could arise if `limitFilesOpen` was not initialized. Before calling `iOS_system` commands, it is recommanded to call `initializeEnvironment()` (once per application) to set up some environment variables and initialize some data structures.

**Comment by terrychou** [comment]
Yes, that was the cause. It never showed after I called `initializeEnvironment()`.

**Comment by holzschu** [comment]
You'll probably want to reinitialize some environment variables after calling `initializeEnvironment()` as, if I remember correctly, we don't work with the same assumptions regarding `$HOME` (both assumptions are good, but mixing them can have unintended consequences).

**Comment by terrychou** [comment]
I will pay attention to this, thanks for reminding.
